const editRoot="https://github.com/polo-potato/madmenbxl/edit/main/",editor=document.querySelector("#markdown"),toast=document.querySelector("#toast"),mapStudio=document.querySelector("#map-studio"),mapCanvas=document.querySelector("#map-canvas"),mapInspector=document.querySelector("#map-inspector"),elementLibrary=document.querySelector("#element-library");let current="story";let historyStates=[],historyIndex=-1,historyTimer=null,mapHeader="",mapElements=[],mapCatalog={},selectedMapId="",selectedPartId="";
const modules={
map:{file:"prologue-map.md",legend:`<p class="kicker">MAP TAGS</p><section class="tag"><code>---</code><b>NEW MAP ITEM</b></section><section class="tag"><code>[ELEMENT] desk</code><b>UNIQUE NAME</b></section><section class="tag"><code>[SHAPE] rect</code><b>DRAWING PRIMITIVE</b><p>rect, ellipse, line, window, dot, text, triangle, laptop or smoke.</p></section><section class="tag"><code>[X] 46 / [Y] 44</code><b>POSITION</b></section><section class="tag"><code>[WIDTH] 118</code><b>SIZE</b></section><section class="tag"><code>[SHOW] coffee</code><b>ACTION-DRIVEN VISIBILITY</b><p>Must match a PROP tag in actions.md.</p></section><section class="tag"><code>[ATTACH] player</code><b>FOLLOW THE PLAYER</b></section><section class="tag"><code>[POSITION] window 177 10</code><b>MOVEMENT TARGET</b><p>Must match a MOVE tag in actions.md.</p></section>`,counts:s=>[["ELEMENTS",/^\[ELEMENT\]/gm],["POSITIONS",/^\[POSITION\]/gm],["ACTION LINKS",/^\[(?:SHOW|ATTACH)\]/gm]]},
story:{file:"prologue.md",legend:`<p class="kicker">PROLOGUE TAGS</p><section class="tag"><code>---</code><b>NEW SCENE</b></section><section class="tag"><code>## TEXT</code><b>SCREEN COPY</b></section><section class="tag thought"><code>[THOUGHT]</code><b>YOU WRITE</b><p>Player types. WHAT IF is automatic.</p></section><section class="tag narration"><code>[NARRATION]</code><b>LIFE HAPPENS</b><p>Italic and automatic.</p></section><section class="tag"><code>[ACTION] check phone</code><b>PAUSE HERE</b><p>Works before, during or after text. Click, then continue below.</p></section><section class="tag unlock"><code>[UNLOCK] scroll</code><b>PERMANENT ACTION</b><p>Attach directly after an action.</p></section><div class="rules"><b>SCENE</b><pre>---\n[NARRATION]\n## TEXT\nfirst words.\n\n[ACTION] continue\n\nmore words.</pre></div>`,counts:s=>[["SCENES",/^---$/gm],["ACTIONS",/^\[ACTION\]/gm],["UNLOCKS",/^\[UNLOCK\]/gm]]},
gauges:{file:"prologue-gauges.md",legend:`<p class="kicker">PROLOGUE GAUGES</p><section class="tag"><code>---</code><b>NEW GAUGE</b></section><section class="tag"><code>[IDEA BASE] 2</code><b>FORMULA BASE</b></section><section class="tag"><code>[IDEA MINIMUM GAIN] 9</code><b>MINIMUM PER TRY</b></section><section class="tag"><code>[GAUGE] creativity</code><b>GAUGE ID</b></section><section class="tag"><code>[START] 48</code><b>INITIAL VALUE</b></section><section class="tag"><code>[DRIFT] -0.025</code><b>CHANGE PER SECOND</b></section><section class="tag"><code>[TRY MINIMUM] 12</code><b>REQUIRED TO TRY</b></section><section class="tag"><code>[TRY COST] -12</code><b>COST PER DIRECTION</b></section><section class="tag"><code>[IDEA SOURCE] +0.14</code><b>DIRECT IDEA SOURCE</b><p>Use this for creativity: without a source, IDEA cannot move.</p></section><section class="tag"><code>[IDEA BOOST] +0.006</code><b>SPEED BOOST</b><p>Energy and stress multiply the source without creating IDEA alone.</p></section><section class="tag narration"><code>## PURPOSE</code><b>HUMAN EXPLANATION</b></section>`,counts:s=>[["GAUGES",/^\[GAUGE\]/gm],["RULES",/^\[(?:START|DRIFT|TRY MINIMUM|TRY COST|IDEA SOURCE|IDEA BOOST)\]/gm]]},
brief:{file:"brief.md",legend:`<p class="kicker">BRIEF TAGS</p><section class="tag"><code>## VISIBLE ACTIONS</code><b>MODULE ACTION MENU</b><p>Add one action per line with -. Names must match actions.md.</p></section><section class="tag"><code>[LABEL] BRIEF</code><b>SMALL LABEL</b></section><section class="tag"><code>[PREFIX] WHAT IF...</code><b>THOUGHT PREFIX</b></section><section class="tag"><code>[SEND] send it</code><b>FINAL BUTTON</b></section><section class="tag"><code>[PROMPT] waiting felt useful?</code><b>PLAYER THOUGHT</b></section><section class="tag"><code>[ACTION] try a direction</code><b>IDEA BUTTON</b></section><section class="tag"><code>[METER] IDEA</code><b>GAUGE NAME</b></section><section class="tag"><code>[COMPLETE] there it is.</code><b>SUCCESS COPY</b></section><div class="rules"><b>MODULE ACTIONS</b><pre>## VISIBLE ACTIONS\n\n- cigarette\n- coffee\n- eat</pre><p>These appear when the module begins. Define their effects once in actions.md.</p></div>`,counts:s=>[["FIELDS",/^\[(?:LABEL|PREFIX|PROMPT|ACTION|METER|COMPLETE|SEND)\]/gm],["VISIBLE ACTIONS",/^\s*-\s+.+$/gm]]},
actions:{file:"actions.md",legend:`<p class="kicker">ACTION TAGS</p><section class="tag"><code>---</code><b>NEW ACTION</b></section><section class="tag unlock"><code>[ACTION] cigarette</code><b>GLOBAL ACTION</b></section><section class="tag"><code>[EFFECT] stress -5</code><b>NORMAL GAUGE CHANGE</b><p>Use + to boost, − to reduce.</p></section><section class="tag"><code>[CHANCE] 0.1</code><b>LUCKY CHANCE</b><p>0.1 means roughly one time in ten.</p></section><section class="tag"><code>[LUCKY EFFECT] creativity +19</code><b>LUCKY GAUGE CHANGE</b><p>Replaces normal effects when luck triggers.</p></section><section class="tag narration"><code>## NOTE</code><b>NORMAL MESSAGE POOL</b><p>Write one option per line, beginning with -</p></section><section class="tag narration"><code>## LUCKY NOTE</code><b>LUCKY MESSAGE POOL</b><p>Same format for the rare outcome.</p></section><div class="rules"><b>RANDOM ACTION</b><pre>---\n[ACTION] scroll\n[EFFECT] creativity -5\n[CHANCE] 0.1\n[LUCKY EFFECT] creativity +19\n## NOTE\n- just noise.\n- another dog.\n## LUCKY NOTE\n- wait. that was good.\n- save that.</pre></div>`,counts:s=>[["ACTIONS",/^\[ACTION\]/gm],["EFFECTS",/^\[(?:EFFECT|LUCKY EFFECT)\]/gm],["CHANCES",/^\[CHANCE\]/gm],["MESSAGES",/^\s*-\s+.+$/gm]]},
events:{file:"events.md",legend:`<p class="kicker">EVENT TAGS</p><section class="tag"><code>---</code><b>NEW EVENT</b></section><section class="tag"><code>[EVENT] event title</code><b>INTERNAL TITLE</b><p>Organises the file; not shown to the player.</p></section><section class="tag narration"><code>## TEXT</code><b>WHAT HAPPENS</b></section><section class="tag"><code>[CHOICE] open the window</code><b>CONTEXT BUTTON</b></section><section class="tag"><code>[EFFECT] stress -4</code><b>CONSEQUENCE</b></section><section class="tag unlock"><code>[UNLOCK] take a walk</code><b>OPTIONAL PERMANENT ACTION</b></section><section class="tag narration"><code>## RESULT</code><b>AFTER THE CHOICE</b></section>`,counts:s=>[["EVENTS",/^\[EVENT\]/gm],["CHOICES",/^\[CHOICE\]/gm],["EFFECTS",/^\[EFFECT\]/gm]]}
};
modules.actions.legend=modules.actions.legend.replace('<section class="tag"><code>[CHANCE] 0.1</code>',`<section class="tag"><code>[COOLDOWN] 20</code><b>WAIT TIME</b><p>Seconds before reuse and before its map state disappears.</p></section><section class="tag"><code>[MOVE] window</code><b>PLAYER POSITION</b></section><section class="tag"><code>[PROP] coffee</code><b>MAP OBJECT</b></section><section class="tag"><code>[ANIMATION] smoke</code><b>MAP ANIMATION</b></section><section class="tag"><code>[CHANCE] 0.1</code>`);
modules.elements={file:"prologue-elements.md",legend:`<p class="kicker">ELEMENT LIBRARY</p><section class="tag"><code>[ELEMENT] desk</code><b>REUSABLE ELEMENT</b></section><section class="tag"><code>[SHAPE] rect</code><b>VISUAL FORM</b></section><section class="tag"><code>[WIDTH] 118</code><b>DEFAULT SIZE</b></section><section class="tag"><code>[SHOW] coffee</code><b>ACTION PROP</b></section><section class="tag"><code>[ATTACH] player</code><b>FOLLOW PLAYER</b></section><p class="rules">Create and design elements here. Place them in the Map module.</p>`,counts:s=>[["ELEMENTS",/^\[ELEMENT\]/gm],["SHAPES",/^\[SHAPE\]/gm],["ACTION LINKS",/^\[(?:SHOW|ATTACH)\]/gm]]};
modules.map.legend=`<p class="kicker">MAP PLACEMENT</p><section class="tag"><code>[PLACE] desk</code><b>PLACE AN ELEMENT</b><p>Must exist in Elements.</p></section><section class="tag"><code>[X] 46 / [Y] 44</code><b>POSITION</b></section><section class="tag"><code>[POSITION] window 177 10</code><b>PLAYER DESTINATION</b></section><p class="rules">The Map only places elements. Create or resize them in Elements.</p>`;
modules.map.counts=s=>[["PLACED",/^\[PLACE\]/gm],["POSITIONS",/^\[POSITION\]/gm]];
const mapTag=(block,name)=>block.match(new RegExp(`^\\[${name}\\]\\s+(.+)$`,"m"))?.[1]?.trim()||"";
function parseMapEditor(){
  const parts=editor.value.split(/^---$/m);mapHeader=parts.shift()?.trim()||"";
  if(current==="elements")mapElements=parts.map(block=>{const id=mapTag(block,"ELEMENT");if(!id)return null;const start=block.search(/^\[PART\]/m),head=start<0?block:block.slice(0,start);const shapes=[...block.matchAll(/^\[PART\]\s+(.+?)\n([\s\S]*?)(?=^\[PART\]|$)/gm)].map(match=>({id:match[1].trim(),shape:mapTag(match[2],"SHAPE")||"rect",x:Number(mapTag(match[2],"X")||0),y:Number(mapTag(match[2],"Y")||0),width:Number(mapTag(match[2],"WIDTH")||0),height:Number(mapTag(match[2],"HEIGHT")||0),text:mapTag(match[2],"TEXT")}));return{id,width:Number(mapTag(head,"WIDTH")||80),height:Number(mapTag(head,"HEIGHT")||60),show:mapTag(head,"SHOW"),attach:mapTag(head,"ATTACH"),parts:shapes}}).filter(Boolean);
  else mapElements=parts.map((block,index)=>{const id=mapTag(block,"PLACE");if(!id)return null;return{...(mapCatalog[id]||{id,width:50,height:40,parts:[]}),id,instance:mapTag(block,"INSTANCE")||`${id}-${index+1}`,x:Number(mapTag(block,"X")||0),y:Number(mapTag(block,"Y")||0)}}).filter(Boolean);
  const key=item=>current==="map"?item.instance:item.id;if(!mapElements.some(item=>key(item)===selectedMapId))selectedMapId=mapElements[0]?key(mapElements[0]):"";
}
function serializeMapEditor(){
  const part=p=>[`[PART] ${p.id}`,`[SHAPE] ${p.shape}`,`[X] ${Math.round(p.x)}`,`[Y] ${Math.round(p.y)}`,p.width?`[WIDTH] ${Math.round(p.width)}`:"",p.height?`[HEIGHT] ${Math.round(p.height)}`:"",p.text?`[TEXT] ${p.text}`:""].filter(Boolean).join("\n");
  const tags=item=>(current==="elements"?[`[ELEMENT] ${item.id}`,`[WIDTH] ${Math.round(item.width)}`,`[HEIGHT] ${Math.round(item.height)}`,item.show?`[SHOW] ${item.show}`:"",item.attach?`[ATTACH] ${item.attach}`:"",...(item.parts||[]).map(part)].filter(Boolean):[`[PLACE] ${item.id}`,`[INSTANCE] ${item.instance}`,`[X] ${Math.round(item.x)}`,`[Y] ${Math.round(item.y)}`]).join("\n");
  editor.value=[mapHeader,...mapElements.map(tags)].join("\n\n---\n").trim()+"\n";
}
function renderMapEditor(){
  const selected=current==="map"?mapElements.find(entry=>entry.instance===selectedMapId):mapElements.find(entry=>entry.id===selectedMapId);const width=current==="elements"?(selected?.width||160):Number(mapTag(mapHeader,"MAP WIDTH")||280),height=current==="elements"?(selected?.height||120):Number(mapTag(mapHeader,"MAP HEIGHT")||360);mapCanvas.style.width=`${width}px`;mapCanvas.style.height=`${height}px`;
  const drawPart=(part,parent="")=>`<span class="studio-element ${part.shape} ${part.id===selectedPartId?'selected':''}" data-part-id="${part.id}" ${parent?`data-map-id="${parent}"`:''} style="left:${part.x}px;top:${part.y}px;${part.width?`width:${part.width}px;`:''}${part.height?`height:${part.height}px;`:''}">${part.text||''}</span>`;
  mapCanvas.innerHTML=current==="elements"?(selected?.parts||[]).map(p=>drawPart(p)).join(""):mapElements.map(item=>`<span class="studio-composite ${item.instance===selectedMapId?'selected':''}" data-map-id="${item.instance}" style="left:${item.x}px;top:${item.y}px;width:${item.width}px;height:${item.height}px">${(item.parts||[]).map(p=>drawPart(p,item.instance)).join('')}<em>${item.instance}</em></span>`).join("");
  elementLibrary.innerHTML=`<p class="kicker">${current==="elements"?'ELEMENTS':'LIBRARY'}</p>${(current==="elements"?mapElements:Object.values(mapCatalog)).map(item=>`<button type="button" data-library-id="${item.id}" class="${item.id===(selected?.id||'')?'active':''}">${item.id}</button>`).join('')}`;
  const item=selected;if(!item){mapInspector.innerHTML='<p class="kicker">SELECT OR CREATE AN ELEMENT</p>';return;}
  const shapes=["rect","rect-muted","ellipse","line","window","dot","text","triangle","laptop","smoke"];
  const chosen=(item.parts||[]).find(p=>p.id===selectedPartId);mapInspector.innerHTML=current==="map"?`<p class="kicker">PLACED COPY</p><b>${item.id}</b><label>INSTANCE<input name="instance" value="${item.instance}"></label><div class="inspector-grid"><label>X<input name="x" type="number" value="${item.x}"></label><label>Y<input name="y" type="number" value="${item.y}"></label></div>`:chosen?`<p class="kicker">SHAPE IN ${item.id}</p><label>NAME<input name="part-id" value="${chosen.id}"></label><label>SHAPE<select name="shape">${shapes.map(shape=>`<option ${shape===chosen.shape?'selected':''}>${shape}</option>`).join('')}</select></label><div class="inspector-grid"><label>X<input name="x" type="number" value="${chosen.x}"></label><label>Y<input name="y" type="number" value="${chosen.y}"></label><label>WIDTH<input name="width" type="number" value="${chosen.width||''}"></label><label>HEIGHT<input name="height" type="number" value="${chosen.height||''}"></label></div><label>TEXT<input name="text" value="${chosen.text||''}"></label>`:`<p class="kicker">ELEMENT</p><label>NAME<input name="id" value="${item.id}"></label><div class="inspector-grid"><label>CANVAS WIDTH<input name="width" type="number" value="${item.width}"></label><label>CANVAS HEIGHT<input name="height" type="number" value="${item.height}"></label></div><label>SHOW WHEN<input name="show" value="${item.show||''}"></label><label>ATTACH TO<input name="attach" value="${item.attach||''}"></label>`;
}
function syncMapEditor(historyNow=false){serializeMapEditor();renderMapEditor();check();if(historyNow)commitHistory();else scheduleHistory()}
function setMapMode(enabled){document.querySelector(".editor").classList.toggle("map-mode",enabled);document.querySelector(".editor").classList.remove("map-raw-open");mapStudio.hidden=!enabled;document.querySelector("#map-add").textContent=current==="map"?"[ PLACE SELECTED ]":"[ + ELEMENT ]";document.querySelector("#part-add").hidden=current!=="elements";document.querySelector("#map-duplicate").hidden=current!=="map";if(enabled){parseMapEditor();renderMapEditor()}}
function message(text){toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3200)}
function check(){const m=modules[current],source=editor.value;document.querySelector("#detected").innerHTML=`<span>LIVE CHECK</span>`+m.counts(source).map(([name,re])=>`<b>${(source.match(re)||[]).length}</b><small>${name}</small>`).join("");document.querySelector("#state").textContent="UNSAVED CHANGES"}
async function load(){const m=modules[current];document.querySelector("#guide").innerHTML=m.legend;document.querySelector("#path").textContent=`content/${m.file}`;document.querySelectorAll("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===current));const response=await fetch(`../content/${m.file}?v=${Date.now()}`);editor.value=await response.text();if(current==="map"){const source=await fetch(`../content/prologue-elements.md?v=${Date.now()}`).then(r=>r.text()),blocks=source.split(/^---$/m).slice(1);mapCatalog=Object.fromEntries(blocks.map(block=>{const id=mapTag(block,"ELEMENT");if(!id)return null;const start=block.search(/^\[PART\]/m),head=start<0?block:block.slice(0,start),parts=[...block.matchAll(/^\[PART\]\s+(.+?)\n([\s\S]*?)(?=^\[PART\]|$)/gm)].map(match=>({id:match[1].trim(),shape:mapTag(match[2],"SHAPE")||"rect",x:Number(mapTag(match[2],"X")||0),y:Number(mapTag(match[2],"Y")||0),width:Number(mapTag(match[2],"WIDTH")||0),height:Number(mapTag(match[2],"HEIGHT")||0),text:mapTag(match[2],"TEXT")}));return[id,{id,width:Number(mapTag(head,"WIDTH")||80),height:Number(mapTag(head,"HEIGHT")||60),show:mapTag(head,"SHOW"),attach:mapTag(head,"ATTACH"),parts}]}).filter(Boolean))}setMapMode(current==="map"||current==="elements");resetHistory();check();document.querySelector("#state").textContent="LOADED FROM GITHUB"}
function renderNavigation(manifest){const globals=`<p class="nav-label">GLOBAL</p>${manifest.globals.map(item=>`<button data-module="${item.id}">${item.label}</button>`).join("")}`;const eras=`<p class="nav-label">ERAS</p>${manifest.eras.map(era=>`<div class="era ${era.status}"><div class="era-title"><b>${era.label}</b><small>${era.status}</small></div>${era.modules.map(item=>`<button data-module="${item.id}">↳ ${item.label}</button>`).join("")}</div>`).join("")}`;document.querySelector(".modules").innerHTML=globals+eras}
document.querySelector("#guide").addEventListener("mousedown",e=>{if(e.target.closest(".tag code"))e.preventDefault()});
document.querySelector("#guide").addEventListener("click",e=>{const code=e.target.closest(".tag code");if(!code)return;const start=editor.selectionStart,end=editor.selectionEnd,tag=code.textContent.trim();const before=editor.value.slice(0,start),after=editor.value.slice(end),prefix=before&&!before.endsWith("\n")?"\n":"",suffix=after&&!after.startsWith("\n")?"\n":"",insertion=prefix+tag+suffix;editor.focus();editor.setRangeText(insertion,start,end,"end");commitHistory();check();message(`${tag} INSERTED`)});
function resetHistory(){clearTimeout(historyTimer);historyStates=[editor.value];historyIndex=0}
function commitHistory(){clearTimeout(historyTimer);if(historyStates[historyIndex]===editor.value)return;historyStates=historyStates.slice(0,historyIndex+1);historyStates.push(editor.value);historyIndex++}
function scheduleHistory(){clearTimeout(historyTimer);historyTimer=setTimeout(commitHistory,350)}
function history(command){commitHistory();const target=command==="undo"?historyIndex-1:historyIndex+1;if(target<0||target>=historyStates.length)return;historyIndex=target;editor.value=historyStates[historyIndex];if(current==="map"||current==="elements"){parseMapEditor();renderMapEditor()}else{editor.focus();editor.setSelectionRange(editor.value.length,editor.value.length)}check()}
document.querySelector("#undo").addEventListener("mousedown",e=>e.preventDefault());document.querySelector("#redo").addEventListener("mousedown",e=>e.preventDefault());document.querySelector("#undo").addEventListener("click",()=>history("undo"));document.querySelector("#redo").addEventListener("click",()=>history("redo"));
editor.addEventListener("keydown",e=>{if(!(e.metaKey||e.ctrlKey)||e.key.toLowerCase()!=="z")return;e.preventDefault();history(e.shiftKey?"redo":"undo")});
document.querySelector(".modules").addEventListener("click",e=>{const b=e.target.closest("[data-module]");if(!b)return;current=b.dataset.module;load().catch(()=>message("COULD NOT LOAD MODULE"))});editor.addEventListener("input",()=>{check();scheduleHistory()});document.querySelector("#reload").addEventListener("click",load);document.querySelector("#publish").addEventListener("click",async()=>{const file=modules[current].file;await navigator.clipboard.writeText(editor.value);message("MODULE COPIED — PASTE IT IN GITHUB");window.open(editRoot+"content/"+file,"_blank","noopener")});
mapCanvas.addEventListener("pointerdown",e=>{const shape=e.target.closest("[data-part-id]"),composite=e.target.closest("[data-map-id]");if(current==="elements"&&!shape)return;if(current==="map"&&!composite)return;e.preventDefault();let item;if(current==="elements"){selectedPartId=shape.dataset.partId;item=mapElements.find(x=>x.id===selectedMapId).parts.find(x=>x.id===selectedPartId)}else{selectedMapId=composite.dataset.mapId;item=mapElements.find(x=>x.instance===selectedMapId)}renderMapEditor();const startX=e.clientX,startY=e.clientY,originX=item.x,originY=item.y;const move=event=>{item.x=Math.round(originX+event.clientX-startX);item.y=Math.round(originY+event.clientY-startY);serializeMapEditor();renderMapEditor();check()};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);commitHistory()};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)});
elementLibrary.addEventListener("click",e=>{const button=e.target.closest("[data-library-id]");if(!button)return;selectedMapId=button.dataset.libraryId;if(current==="elements")selectedPartId="";renderMapEditor()});
mapInspector.addEventListener("input",e=>{const item=current==="map"?mapElements.find(x=>x.instance===selectedMapId):mapElements.find(x=>x.id===selectedMapId);if(!item)return;const name=e.target.name,value=["x","y","width","height"].includes(name)?Number(e.target.value||0):e.target.value.trim(),part=(item.parts||[]).find(x=>x.id===selectedPartId);if(part&&["part-id","shape","x","y","width","height","text"].includes(name)){if(name==="part-id"){part.id=value;selectedPartId=value}else part[name]=value}else{const old=item.id;item[name]=value;if(name==="id"){selectedMapId=value||old;if(!value)item.id=old}else if(name==="instance")selectedMapId=value}syncMapEditor()});
document.querySelector("#map-add").addEventListener("click",()=>{if(current==="map"){const base=mapCatalog[selectedMapId]||Object.values(mapCatalog)[0];if(!base)return;let n=1,instance=`${base.id}-${n}`;while(mapElements.some(x=>x.instance===instance))instance=`${base.id}-${++n}`;mapElements.push({...structuredClone(base),instance,x:20,y:20});selectedMapId=instance}else{let n=1,id="element";while(mapElements.some(x=>x.id===id))id=`element-${++n}`;mapElements.push({id,width:100,height:70,show:"",attach:"",parts:[]});selectedMapId=id;selectedPartId=""}syncMapEditor(true)});
document.querySelector("#part-add").addEventListener("click",()=>{const item=mapElements.find(x=>x.id===selectedMapId);if(!item)return;let n=1,id="shape";while(item.parts.some(x=>x.id===id))id=`shape-${++n}`;item.parts.push({id,shape:"rect",x:10,y:10,width:50,height:30,text:""});selectedPartId=id;syncMapEditor(true)});
document.querySelector("#map-duplicate").addEventListener("click",()=>{const item=mapElements.find(x=>x.instance===selectedMapId);if(!item)return;let n=2,instance=`${item.id}-${n}`;while(mapElements.some(x=>x.instance===instance))instance=`${item.id}-${++n}`;mapElements.push({...structuredClone(item),instance,x:item.x+12,y:item.y+12});selectedMapId=instance;syncMapEditor(true)});
document.querySelector("#map-delete").addEventListener("click",()=>{if(current==="elements"&&selectedPartId){const item=mapElements.find(x=>x.id===selectedMapId);item.parts=item.parts.filter(x=>x.id!==selectedPartId);selectedPartId=""}else{mapElements=mapElements.filter(item=>(current==="map"?item.instance:item.id)!==selectedMapId);selectedMapId=current==="map"?(mapElements[0]?.instance||""):(mapElements[0]?.id||"")}syncMapEditor(true)});
document.querySelector("#map-raw").addEventListener("click",e=>{const panel=document.querySelector(".editor"),opening=!panel.classList.contains("map-raw-open");panel.classList.toggle("map-raw-open",opening);e.currentTarget.textContent=opening?"[ VISUAL MAP ]":"[ RAW MARKDOWN ]";if(!opening){parseMapEditor();renderMapEditor()}else editor.focus()});
fetch(`../content/manifest.json?v=${Date.now()}`).then(r=>r.json()).then(manifest=>{renderNavigation(manifest);return load()}).catch(()=>message("COULD NOT LOAD CONTENT STRUCTURE"));
