const editRoot="https://github.com/polo-potato/madmenbxl/edit/main/",editor=document.querySelector("#markdown"),toast=document.querySelector("#toast");let current="story";let historyStates=[],historyIndex=-1,historyTimer=null;
const modules={
story:{file:"prologue.md",legend:`<p class="kicker">PROLOGUE TAGS</p><section class="tag"><code>---</code><b>NEW SCENE</b></section><section class="tag"><code>## TEXT</code><b>SCREEN COPY</b></section><section class="tag thought"><code>[THOUGHT]</code><b>YOU WRITE</b><p>Player types. WHAT IF is automatic.</p></section><section class="tag narration"><code>[NARRATION]</code><b>LIFE HAPPENS</b><p>Italic and automatic.</p></section><section class="tag"><code>[ACTION] check phone</code><b>PAUSE HERE</b><p>Works before, during or after text. Click, then continue below.</p></section><section class="tag unlock"><code>[UNLOCK] scroll</code><b>PERMANENT ACTION</b><p>Attach directly after an action.</p></section><div class="rules"><b>SCENE</b><pre>---\n[NARRATION]\n## TEXT\nfirst words.\n\n[ACTION] continue\n\nmore words.</pre></div>`,counts:s=>[["SCENES",/^---$/gm],["ACTIONS",/^\[ACTION\]/gm],["UNLOCKS",/^\[UNLOCK\]/gm]]},
gauges:{file:"prologue-gauges.md",legend:`<p class="kicker">PROLOGUE GAUGES</p><section class="tag"><code>---</code><b>NEW GAUGE</b></section><section class="tag"><code>[IDEA BASE] 2</code><b>FORMULA BASE</b></section><section class="tag"><code>[IDEA MINIMUM GAIN] 9</code><b>MINIMUM PER TRY</b></section><section class="tag"><code>[GAUGE] creativity</code><b>GAUGE ID</b></section><section class="tag"><code>[START] 48</code><b>INITIAL VALUE</b></section><section class="tag"><code>[DRIFT] -0.025</code><b>CHANGE PER SECOND</b></section><section class="tag"><code>[TRY MINIMUM] 12</code><b>REQUIRED TO TRY</b></section><section class="tag"><code>[TRY COST] -12</code><b>COST PER DIRECTION</b></section><section class="tag"><code>[IDEA SOURCE] +0.14</code><b>DIRECT IDEA SOURCE</b><p>Use this for creativity: without a source, IDEA cannot move.</p></section><section class="tag"><code>[IDEA BOOST] +0.006</code><b>SPEED BOOST</b><p>Energy and stress multiply the source without creating IDEA alone.</p></section><section class="tag narration"><code>## PURPOSE</code><b>HUMAN EXPLANATION</b></section>`,counts:s=>[["GAUGES",/^\[GAUGE\]/gm],["RULES",/^\[(?:START|DRIFT|TRY MINIMUM|TRY COST|IDEA SOURCE|IDEA BOOST)\]/gm]]},
brief:{file:"brief.md",legend:`<p class="kicker">BRIEF TAGS</p><section class="tag"><code>[LABEL] BRIEF</code><b>SMALL LABEL</b></section><section class="tag"><code>[PREFIX] WHAT IF...</code><b>THOUGHT PREFIX</b></section><section class="tag"><code>[SEND] send it</code><b>FINAL BUTTON</b></section><section class="tag"><code>[PROMPT] waiting felt useful?</code><b>PLAYER THOUGHT</b></section><section class="tag"><code>[ACTION] try a direction</code><b>IDEA BUTTON</b></section><section class="tag"><code>[METER] IDEA</code><b>GAUGE NAME</b></section><section class="tag"><code>[COMPLETE] there it is.</code><b>SUCCESS COPY</b></section><div class="rules"><p>One line per interface element. Keep the tag; change what follows it.</p></div>`,counts:s=>[["FIELDS",/^\[(?:LABEL|PREFIX|PROMPT|ACTION|METER|COMPLETE|SEND)\]/gm]]},
actions:{file:"actions.md",legend:`<p class="kicker">ACTION TAGS</p><section class="tag"><code>---</code><b>NEW ACTION</b></section><section class="tag unlock"><code>[ACTION] cigarette</code><b>GLOBAL ACTION</b></section><section class="tag"><code>[EFFECT] stress -5</code><b>NORMAL GAUGE CHANGE</b><p>Use + to boost, − to reduce.</p></section><section class="tag"><code>[CHANCE] 0.1</code><b>LUCKY CHANCE</b><p>0.1 means roughly one time in ten.</p></section><section class="tag"><code>[LUCKY EFFECT] creativity +19</code><b>LUCKY GAUGE CHANGE</b><p>Replaces normal effects when luck triggers.</p></section><section class="tag narration"><code>## NOTE</code><b>NORMAL MESSAGE POOL</b><p>Write one option per line, beginning with -</p></section><section class="tag narration"><code>## LUCKY NOTE</code><b>LUCKY MESSAGE POOL</b><p>Same format for the rare outcome.</p></section><div class="rules"><b>RANDOM ACTION</b><pre>---\n[ACTION] scroll\n[EFFECT] creativity -5\n[CHANCE] 0.1\n[LUCKY EFFECT] creativity +19\n## NOTE\n- just noise.\n- another dog.\n## LUCKY NOTE\n- wait. that was good.\n- save that.</pre></div>`,counts:s=>[["ACTIONS",/^\[ACTION\]/gm],["EFFECTS",/^\[(?:EFFECT|LUCKY EFFECT)\]/gm],["CHANCES",/^\[CHANCE\]/gm],["MESSAGES",/^\s*-\s+.+$/gm]]},
events:{file:"events.md",legend:`<p class="kicker">EVENT TAGS</p><section class="tag"><code>---</code><b>NEW EVENT</b></section><section class="tag"><code>[EVENT] event title</code><b>INTERNAL TITLE</b><p>Organises the file; not shown to the player.</p></section><section class="tag narration"><code>## TEXT</code><b>WHAT HAPPENS</b></section><section class="tag"><code>[CHOICE] open the window</code><b>CONTEXT BUTTON</b></section><section class="tag"><code>[EFFECT] stress -4</code><b>CONSEQUENCE</b></section><section class="tag unlock"><code>[UNLOCK] take a walk</code><b>OPTIONAL PERMANENT ACTION</b></section><section class="tag narration"><code>## RESULT</code><b>AFTER THE CHOICE</b></section>`,counts:s=>[["EVENTS",/^\[EVENT\]/gm],["CHOICES",/^\[CHOICE\]/gm],["EFFECTS",/^\[EFFECT\]/gm]]}
};
function message(text){toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3200)}
function check(){const m=modules[current],source=editor.value;document.querySelector("#detected").innerHTML=`<span>LIVE CHECK</span>`+m.counts(source).map(([name,re])=>`<b>${(source.match(re)||[]).length}</b><small>${name}</small>`).join("");document.querySelector("#state").textContent="UNSAVED CHANGES"}
async function load(){const m=modules[current];document.querySelector("#guide").innerHTML=m.legend;document.querySelector("#path").textContent=`content/${m.file}`;document.querySelectorAll("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===current));const response=await fetch(`../content/${m.file}?v=${Date.now()}`);editor.value=await response.text();resetHistory();check();document.querySelector("#state").textContent="LOADED FROM GITHUB"}
function renderNavigation(manifest){const globals=`<p class="nav-label">GLOBAL</p>${manifest.globals.map(item=>`<button data-module="${item.id}">${item.label}</button>`).join("")}`;const eras=`<p class="nav-label">ERAS</p>${manifest.eras.map(era=>`<div class="era ${era.status}"><div class="era-title"><b>${era.label}</b><small>${era.status}</small></div>${era.modules.map(item=>`<button data-module="${item.id}">↳ ${item.label}</button>`).join("")}</div>`).join("")}`;document.querySelector(".modules").innerHTML=globals+eras}
document.querySelector("#guide").addEventListener("mousedown",e=>{if(e.target.closest(".tag code"))e.preventDefault()});
document.querySelector("#guide").addEventListener("click",e=>{const code=e.target.closest(".tag code");if(!code)return;const start=editor.selectionStart,end=editor.selectionEnd,tag=code.textContent.trim();const before=editor.value.slice(0,start),after=editor.value.slice(end),prefix=before&&!before.endsWith("\n")?"\n":"",suffix=after&&!after.startsWith("\n")?"\n":"",insertion=prefix+tag+suffix;editor.focus();editor.setRangeText(insertion,start,end,"end");commitHistory();check();message(`${tag} INSERTED`)});
function resetHistory(){clearTimeout(historyTimer);historyStates=[editor.value];historyIndex=0}
function commitHistory(){clearTimeout(historyTimer);if(historyStates[historyIndex]===editor.value)return;historyStates=historyStates.slice(0,historyIndex+1);historyStates.push(editor.value);historyIndex++}
function scheduleHistory(){clearTimeout(historyTimer);historyTimer=setTimeout(commitHistory,350)}
function history(command){commitHistory();const target=command==="undo"?historyIndex-1:historyIndex+1;if(target<0||target>=historyStates.length)return;historyIndex=target;editor.value=historyStates[historyIndex];editor.focus();editor.setSelectionRange(editor.value.length,editor.value.length);check()}
document.querySelector("#undo").addEventListener("mousedown",e=>e.preventDefault());document.querySelector("#redo").addEventListener("mousedown",e=>e.preventDefault());document.querySelector("#undo").addEventListener("click",()=>history("undo"));document.querySelector("#redo").addEventListener("click",()=>history("redo"));
editor.addEventListener("keydown",e=>{if(!(e.metaKey||e.ctrlKey)||e.key.toLowerCase()!=="z")return;e.preventDefault();history(e.shiftKey?"redo":"undo")});
document.querySelector(".modules").addEventListener("click",e=>{const b=e.target.closest("[data-module]");if(!b)return;current=b.dataset.module;load().catch(()=>message("COULD NOT LOAD MODULE"))});editor.addEventListener("input",()=>{check();scheduleHistory()});document.querySelector("#reload").addEventListener("click",load);document.querySelector("#publish").addEventListener("click",async()=>{const file=modules[current].file;await navigator.clipboard.writeText(editor.value);message("MODULE COPIED — PASTE IT IN GITHUB");window.open(editRoot+"content/"+file,"_blank","noopener")});
fetch(`../content/manifest.json?v=${Date.now()}`).then(r=>r.json()).then(manifest=>{renderNavigation(manifest);return load()}).catch(()=>message("COULD NOT LOAD CONTENT STRUCTURE"));
